### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Naman9Bhardwaj9** [AmaanC/music-recommender#4]
i am an absolute begginer please can you specify the steps to run thhis project

**Comment by AmaanC** [comment]
This was a very quick hacky project, and I don't really have the bandwidth to set it up again to confirm my setup instructions, but you'll need to install any missing python packages (from PyPi), such as Flask, Pandas, SciPy, SQLAlchemy, etc.
Then setup PostgreSQL with a DB named `testdb`.

After that, you can do `python app.py` and it should just work (but well may not, given that I hadn't pinned the package dependencies to specific versions back when I worked on this).

Sorry about that, but that's all I can offer for an old abandoned project!

**Comment by Naman9Bhardwaj9** [comment]
thanks
i have installed all the dependencies what i am confused about is running
it on my pycharm ide
should i open the.py file and run it or open it in jupyter notebook

**Comment by AmaanC** [comment]
Neither. You run it from the command line: `python3 app.py` for eg.

**Comment by Naman9Bhardwaj9** [comment]
Hey,

I just signed the petition "MHRD INDIA: M tech Fee hike, Take it Back." and
wanted to see if you could help by adding your name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/pm5fGxvkLk

Thanks!
Naman
